name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK (install cmdline-tools and basic packages)
        uses: android-actions/setup-android@v3
        with:
          api-levels: '34'
          build-tools: '34.0.0'
          ndk: ''

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Create Gradle wrapper (if not present) and build debug APK
        run: |
          gradle wrapper --gradle-version 8.6 || true
          ./gradlew :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
